name: Deploy with HexoJS

on:
  push:
    branches: [ "posts" ]

# cancel previous workflows, run only one workflow
concurrency:
  group: deploy-${{ github.event.push.number || github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Asia/Jakarta"
        timezoneMacos: "Asia/Jakarta"
        timezoneWindows: "Western Indonesia Time"
    - uses: actions/checkout@v3
      with:
        repository: dimaslanjaka/static-blog-generator-hexo
        ref: master
        token: "${{ secrets.GITHUB_TOKEN }}"
        submodules: recursive
    - name: Declare some variables
      id: vars
      shell: bash
      run: |
        echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        echo "::set-output name=hash::$(git rev-parse --short HEAD)"
        echo "::set-output name=yarn::$(yarn cache dir)"
        echo "::set-output name=npm::$(npm config get cache)"
        echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - uses: actions/cache@v3
      with:
        path: |
          ${{ steps.vars.outputs.npm }}
          ./tmp
          ./node_modules
          ./.deploy_git
          ./db.json
          ./public
        key: ${{ runner.os }}-${{ hashFiles('.gitid') }}
        
    - name: Resolve git user
      continue-on-error: true
      run: |
        git config --global user.email "dimaslanjaka@gmail.com"
        git config --global user.name "dimaslanjaka"
        git config --global init.defaultBranch master
        git submodule foreach git pull
          
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        
    - name: Install System
      run: |
        sudo apt-get install software-properties-common -y
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update -y
        sudo apt-get install gcc-4.9 -y
        sudo apt-get install libssl-dev -y
        sudo apt-get install libstdc++-4.9-dev -y
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 50
        sudo apt-get install g++-4.9 -y
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 50

    - name: Build
      run: |
        npm i gulp-cli typescript npm ts-node hexo-cli yarn typescript --location=global
        npm i -D https://github.com/dimaslanjaka/static-blog-generator/raw/master/release/development.tgz
        npm i -D https://github.com/dimaslanjaka/hexo-post-parser.git
        npm i -D https://github.com/dimaslanjaka/safelink.git
        npm i https://github.com/dimaslanjaka/hexo-adsense.git
        npm install
        npx sbg copy --nocache
        npx hexo generate
        npx gulp safelink
        npx sbg deploy --nocache --verbose
        
    - name: Deploy
      continue-on-error: true
      working-directory: .deploy_git
      run: |
        git add -A
        git commit -m "update site ${{ steps.vars.outputs.date }}\nfrom: https://github.com/dimaslanjaka/dimaslanjaka/tree/commit/${{ steps.vars.outputs.hash }}"
        git push
